#!/usr/bin/env python3

# TODO

import os
import sys
import helpers
import nltk

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets word")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    #get tweets
    
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    if tweets == None:
        print("exit")
        sys.exit(3)


    for tweet in tweets:

        # analyze word
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}, @{}".format(score, tweet, sys.argv[1]), "green"))
        elif score < 0.0:
            print(colored("{} {}, @{}".format(score, tweet, sys.argv[1]), "red"))
        else:
            print(colored("{} {}, @{}".format(score, tweet, sys.argv[1]), "yellow"))

if __name__ == "__main__":
    main()
